---
language: python
python:   "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  # Test functionality with default values
  - ansible-playbook tests/test_defaults.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_defaults.yml -i localhost, --connection=local --sudo

  # Test celery task along with supervisor
  - ansible-playbook tests/test_supervisor.yml -i localhost, --syntax-check 
  - ansible-playbook tests/test_supervisor.yml -i localhost, --connection=local --sudo

# vi:ts=2:sw=2:et:ft=yaml
