---
language: python
python:   "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - ansible-playbook test/test.yml -i test/inventory --syntax-check 
  - ansible-playbook test/test.yml -i test/inventory --connection=local --sudo -vvv

