---

- name: Install Flower
  pip:
    name=flower
    version={{celery_flower_version}}

- name: Supervice Flower
  template:
    src=etc/supervisor/conf.d/celery.conf.j2
    dest=/etc/supervisor/conf.d/flower.conf
    owner="root"
    group="root"
    mode="0644"
  with_dict: celery_flower_service
  notify: supervisor restart

# vi:ts=2:sw=2:et:ft=yaml
