---
#
# Install celery and deps
#

- name: Package dependencies
  apt:
    state=present
    name="{{item}}"
    update_cache=yes
    cache_valid_time=3600
  with_items: celery_apt_pkgs

- name: Install Celery
  pip:
    name=celery
    version="{{celery_version}}"

# vi:ts=2:sw=2:et:ft=yaml
