---
#
# Celery role: logrotate configuration file
#

- name: Logrotate file
  template:
    src=etc/logrotate.d/celeryd.conf.j2
    dest=/etc/logrotate.d/celeryd.conf
    owner='root'
    group='root'
    mode='0644'
  when: celery_logrotate

