---

# Check for required vars

- include: install.yml
  tags: celery_install

- include: logrotate.yml
  tags: celery_config

- include: flower.yml
  when: celery_flower_enabled
  tags: celery_flower

# vi:ts=2:sw=2:et:ft=yaml
