---

- name: Package dependencies
  package:
    state: present
    name: "{{item}}"
  with_items: "{{celery_pkg_deps}}"

- name: Install Celery
  pip:
    name: celery
    version: "{{celery_version|default('')}}"

- name: Install Flower
  pip:
    name: flower
    version: "{{celery_flower_version|default(omit)}}"
  when: 
    - celery_flower_enabled is defined
    - celery_flower_enabled

# vi:ts=2:sw=2:et:ft=yaml
