---

# Check for required vars

- name: Check supervisor_services var
  fail: 
    msg="You need to specify supervisor_services dict var"
  when: supervisor_services is not defined

- include: install.yml
  tags: celery_install

- include: supervisor.yml
  tags: celery_supervisor

- include: config.yml
  tags: celery_config

- include: logrotate.yml
  tags: celery_config

- name: Enable Supervisor
  service:
    name=supervisor
    enabled=yes
    state=started

# vi:ts=2:sw=2:et:ft=yaml
